name: Test the Docker image

on:
  push:
    branches: [ "bullseye-slim" ]
  pull_request:
    branches: [ "bullseye-slim" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pulling from Docker Hub
      run: docker pull phanhoang1366/judge-server
      
    - name: Starting the service
      run: | 
        cp docker-compose.example.yml docker-compose.yml
        docker-compose up -d
        docker ps -a
        sleep 10
    
    - name: Testing the compiler
      run: python tests/tests.py
